import Head from "next/head";
import React from "react";

type TProps = {
  pageName: String;
};

export const Header = ({ pageName }: TProps) => {
  return (
    <Head>
      <title>{pageName}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
